### ISSUE TITLE
canon example randomly crashed on my i.MX6Q device

### ISSUE THREAD

**Issue by yf13** [fakenmc/cf4ocl#20]
I downloaded the latest version in master branch and could build it successfully with the 1.1 embedded profile OpenCL library on a Freescale (now NXP) i.MX6Q device. The utilities are running fine and can show the device information correctly:

```
* Platform #0: Vivante OpenCL Platform (Vivante Corporation)
               OpenCL 1.1 , EMBEDDED_PROFILE

    [ Device #0: Vivante OpenCL Device ]

        TYPE                                 | GPU
        VENDOR                               | Vivante Corporation
        OPENCL_C_VERSION                     | OpenCL C 1.1
        MAX_COMPUTE_UNITS                    | 4
        GLOBAL_MEM_SIZE                      | 128.0 MiB (134217728 bytes)
        MAX_MEM_ALLOC_SIZE                   | 64.0 MiB (67108864 bytes)
        LOCAL_MEM_SIZE                       | 1.0 KiB (1024 bytes)
        LOCAL_MEM_TYPE                       | GLOBAL
        MAX_WORK_GROUP_SIZE                  | 1024 work-items
```

However, the canon example sometimes works and most times crashes (note that I added more debug output below:

Working case:

```
  =========================== Device Selection ============================

              0. Vivante OpenCL Device [Vivante OpenCL Platform]

 * Global worksize: 16
 * Local worksize : 16

device buffers created.
device buffer write events added to wait list...
kernel termination event added to wait list...
kernel done, wait list empty.
device result back.
Kernel exec passed result check.

perform profiling...

   =========================== Timming/Profiling ===========================

     Aggregate times by event  :
       ------------------------------------------------------------------
       | Event name                     | Rel. time (%) | Abs. time (s) |
       ------------------------------------------------------------------
       | WRITE_BUFFER                   |       58.8535 |    4.6200e-04 |
       | READ_BUFFER                    |       22.9299 |    1.8000e-04 |
       | MARKER                         |       17.4522 |    1.3700e-04 |
       | NDRANGE_KERNEL                 |        0.7643 |    6.0000e-06 |
       ------------------------------------------------------------------
                                        |         Total |    7.8500e-04 |
                                        ---------------------------------
     Event overlaps            : None
profiling result in out.tsv
host buffers destroyed.
device buffers destroyed.
memory leak check passed.
```

Crash case:

```
   =========================== Device Selection ============================

              0. Vivante OpenCL Device [Vivante OpenCL Platform]

 * Global worksize: 16
 * Local worksize : 16

device buffers created.
device buffer write events added to wait list...
kernel termination event added to wait list...
kernel done, wait list empty.
Segmentation fault (core dumped)
```

The crashing point looks like at the result checking stage. Not sure if this is a cf4ocl issue or FSL OpenCL library issue. Please teach if there are ways to identify it.

**Comment by fakenmc** [comment]
Hi, thanks for the feedback. Unfortunately I currently don't have access to such a board, but I can offer some suggestions for solving this problem. I think the best bet is to build the library and the examples in CMake's Debug mode, and then debug the canon example using gdb (GNU Debugger). Set a breakpoint (b) before where the crash seems to be occurring, and then execute instructions line-by-line (n), until the crash occurs. When you detect the instruction responsible for the crash, repeat the process, but instead of executing that specific instruction (n), step into it (s), and then execute instructions in the called function (n) until you detect the instruction that caused the crash. Repeat this process again until you find the lowest level instruction which is causing the crash. This way you can determine where exactly is the crash occurring, i.e. in Vivante's OpenCL, in cf4ocl, in the canon example, etc.

In parentheses I specified gdb commands. Here's a short list of these and other useful gdb commands:

b / break - Set a breakpoint at a specified line
n / next - Execute next instruction (but don't go into it)
s / step - Execute next instruction and go into it if source available
r / run - Run program
s / stop - Stop running program
q / quit - Quit GDB
set args - Set program args

You invoke gdb like this:

$ gbd name_of_executable

Do let me know if the problem is in cf4ocl or the canon example. The examples run fine on Linux, Mac, and Windows on x86/x86_64 platforms, which is what I have available for testing.

**Comment by fakenmc** [comment]
Closed this issue due to lack of feedback.
